language: cpp
compiler:
  - gcc
  - clang
env:
  global:
   # The next declaration is the encrypted COVERITY_SCAN_TOKEN, created
   # via the "travis encrypt" command using the project repo's public key
  - secure: "B6Qfsm3mx0yUMQFcvQTbW3SliAbrqUwH+jZDj3bQipL9M0UQkXNptmsl33mHMQfi14MGEIspfeYPk8TKPCCJ4Ia7yjE1T/5V01qB8WeJlzUlMFunuhy8G7QJmwS7vPsd0t69563/PMKq4JLEOLGhSwhZPN83pV4G70ctrxn/aG4="
addons:
  coverity_scan:
    project:
      name: "stefanocasazza/ULib"
      description: "C++ application development framework"
    notification_email: stefano.casazza@gmail.com
    build_command_prepend: "CPPFLAGS=-DU_COVERITY_FALSE_POSITIVE ./configure"
    build_command: "make -j2"
    branch_pattern: master
# Change this to your needs
script:
  - ./configure && make -j2
